### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by pford68** [pford68/slf4js#4]
We have no unit tests.

## TODO
- [x] Add a MockLogger/TestLogger for use in the tests to inspect the messages and formatting.
- [x] Make currently private functions testing.   (Some of these are too important not to test.)
- [x] Write tests
- [x] Install Mocha and NYC.

**Comment by pford68** [comment]
I installed gulp-mocha and gulp-istanbul and began writing tests, but the coverage was 6% and never changed.  The issue is that gulp-istanbul is not compatible with gulp-mocha 4.x.  And according to [this ticket](https://github.com/SBoudrias/gulp-istanbul/issues/115) that fact appears unlikely to change.

**Comment by pford68** [comment]
I switched to running `nyc` and `mocha` through NPM.  I am using a `.nycrc` file.  Uninstalled gulp-mocha and gulp-istanbul.

**Comment by pford68** [comment]
We're at 70% coverage as of today.  The following still need tests:
* LoggingDecorator
* LogFormatter.
